### ISSUE TITLE
tests 52-56 and 58

### ISSUE THREAD

**Issue by hu8813** [LucasKuhn/minishell_tester#19]
hi
tests 52-56 and 58 are undefined behaviour, which means it must not be same as bash output or exit code
it may be confusing for some people, trying to implement or ask from evaluated person these undefined behaviour

man exit
man export

kind regards

**Comment by LucasKuhn** [comment]
Could you please describe which specific tests ? 
Do you mean these: 
<img width="975" alt="image" src="https://github.com/LucasKuhn/minishell_tester/assets/26127185/1a4d60ef-53cc-4a33-ad0d-98675513cb89">

**Comment by hu8813** [comment]
thanks for the response, 
Test  52: ❌ exit 9223372036854775807 
Test  53: ✅⚠️  exit 9223372036854775808 
Test  54: ❌ exit -9223372036854775807 
Test  55: ❌ exit -9223372036854775808 
Test  56: ❌ exit -9223372036854775809 
Test  58: ❌ export | sort | grep -v SHLVL | grep -v "declare -x _" | grep -v "PS.=" 

these exit and export tests are undefined behaviours and it doesn't make sense to implement the same behavour

man exit: i.e. exit n: If n is specified, but its value is not between 0 and 255 inclusively, the exit status is undefined.

man export: When no arguments are given, the results are unspecified. the results in the tester is actually with  -p  option

these are undefined behaviours and not need to be implemented

**Comment by LucasKuhn** [comment]
Gotcha! 
Adding reference links:
Exit -> https://man7.org/linux/man-pages/man1/exit.1p.html#EXIT_STATUS
Export -> https://www.man7.org/linux/man-pages/man1/export.1p.html#RATIONALE

> man export: When no arguments are given, the results are unspecified. the results in the tester is actually with -p option

The tester does not save any result, it runs the prompt on your `./minishell` first, then runs the same prompt on the system's bash, and compares the output to give a pass ✅ or an error ❌

Instead of removing these tests, maybe we can move them to the [extras](https://github.com/LucasKuhn/minishell_tester/blob/main/extras) file along with other extra tests 
```
./tester extras 
```

@sgkhusal , can you give me your opinion on this change?

**Comment by sgkhusal** [comment]
I think it is a good solution since it is undefined behavior and it also maintains these case tests referenced to help people ensure they don't break the program 🙂
